// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../model/in_chat/dto/in_chat_event_list_local_dto.dart';
import '../../model/user/dto/user_local_dto.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6929589078566451250),
      name: 'InChatDataLocalDTO',
      lastPropertyId: const obx_int.IdUid(4, 2368925187953414032),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7934234719201775379),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5350857677561821740),
            name: 'dataId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 477196866431152592),
            name: 'inChatDataType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2368925187953414032),
            name: 'contents',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 1727238836425246089),
      name: 'InChatEventListLocalDTO',
      lastPropertyId: const obx_int.IdUid(2, 7958415430520320432),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8102268948635172208),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7958415430520320432),
            name: 'roomId',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(4, 3575284087082992589),
            name: 'userList',
            targetId: const obx_int.IdUid(4, 5115315628866282220)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(5, 9169392636316638828),
            name: 'inChatEventList',
            targetId: const obx_int.IdUid(3, 5310278417568448237))
      ],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 5310278417568448237),
      name: 'InChatEventLocalDTO',
      lastPropertyId: const obx_int.IdUid(9, 1585148969300346690),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1186900153388184028),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8496729147045889852),
            name: 'eventId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8212661422156682553),
            name: 'userId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1224763139463649506),
            name: 'inChatEventType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8284527198821110264),
            name: 'timeStamp',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4266158725092122896),
            name: 'inChatEventStatus',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2268845606986151022),
            name: 'inChatDataId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 3218224958239779237),
            relationTarget: 'InChatDataLocalDTO')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 5115315628866282220),
      name: 'UserLocalDTO',
      lastPropertyId: const obx_int.IdUid(7, 6015609694460064215),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4378815629329486973),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 680523836483137508),
            name: 'userId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8631333855054858109),
            name: 'nickname',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4860547670405281381),
            name: 'stateMsg',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5689427324582082290),
            name: 'profileUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1345729936813278579),
            name: 'mannerTemperature',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(4, 5115315628866282220),
      lastIndexId: const obx_int.IdUid(4, 1320994640446253503),
      lastRelationId: const obx_int.IdUid(5, 9169392636316638828),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [
        5776297819287639768,
        6481614098286429565,
        1320994640446253503
      ],
      retiredPropertyUids: const [
        4690822206809723124,
        1585148969300346690,
        6015609694460064215
      ],
      retiredRelationUids: const [
        2580727865079716615,
        3448847052248615661,
        6655875872615273825
      ],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    InChatDataLocalDTO: obx_int.EntityDefinition<InChatDataLocalDTO>(
        model: _entities[0],
        toOneRelations: (InChatDataLocalDTO object) => [],
        toManyRelations: (InChatDataLocalDTO object) => {},
        getId: (InChatDataLocalDTO object) => object.id,
        setId: (InChatDataLocalDTO object, int id) {
          object.id = id;
        },
        objectToFB: (InChatDataLocalDTO object, fb.Builder fbb) {
          final dataIdOffset = fbb.writeString(object.dataId);
          final inChatDataTypeOffset = fbb.writeString(object.inChatDataType);
          final contentsOffset = fbb.writeString(object.contents);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, dataIdOffset);
          fbb.addOffset(2, inChatDataTypeOffset);
          fbb.addOffset(3, contentsOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dataIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final inChatDataTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final contentsParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final object = InChatDataLocalDTO(
              dataId: dataIdParam,
              inChatDataType: inChatDataTypeParam,
              contents: contentsParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    InChatEventListLocalDTO: obx_int.EntityDefinition<InChatEventListLocalDTO>(
        model: _entities[1],
        toOneRelations: (InChatEventListLocalDTO object) => [],
        toManyRelations: (InChatEventListLocalDTO object) => {
              obx_int.RelInfo<InChatEventListLocalDTO>.toMany(4, object.id):
                  object.userList,
              obx_int.RelInfo<InChatEventListLocalDTO>.toMany(5, object.id):
                  object.inChatEventList
            },
        getId: (InChatEventListLocalDTO object) => object.id,
        setId: (InChatEventListLocalDTO object, int id) {
          object.id = id;
        },
        objectToFB: (InChatEventListLocalDTO object, fb.Builder fbb) {
          final roomIdOffset = fbb.writeString(object.roomId);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, roomIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final roomIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object = InChatEventListLocalDTO(roomId: roomIdParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<InChatEventListLocalDTO>(
              object.userList,
              store,
              obx_int.RelInfo<InChatEventListLocalDTO>.toMany(4, object.id));
          obx_int.InternalToManyAccess.setRelInfo<InChatEventListLocalDTO>(
              object.inChatEventList,
              store,
              obx_int.RelInfo<InChatEventListLocalDTO>.toMany(5, object.id));
          return object;
        }),
    InChatEventLocalDTO: obx_int.EntityDefinition<InChatEventLocalDTO>(
        model: _entities[2],
        toOneRelations: (InChatEventLocalDTO object) => [object.inChatData],
        toManyRelations: (InChatEventLocalDTO object) => {},
        getId: (InChatEventLocalDTO object) => object.id,
        setId: (InChatEventLocalDTO object, int id) {
          object.id = id;
        },
        objectToFB: (InChatEventLocalDTO object, fb.Builder fbb) {
          final userIdOffset = fbb.writeString(object.userId);
          final inChatEventTypeOffset = fbb.writeString(object.inChatEventType);
          final inChatEventStatusOffset =
              fbb.writeString(object.inChatEventStatus);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.eventId);
          fbb.addOffset(2, userIdOffset);
          fbb.addOffset(3, inChatEventTypeOffset);
          fbb.addInt64(4, object.timeStamp.millisecondsSinceEpoch);
          fbb.addOffset(5, inChatEventStatusOffset);
          fbb.addInt64(6, object.inChatData.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final eventIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final userIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final inChatEventTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final timeStampParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final inChatEventStatusParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final object = InChatEventLocalDTO(
              eventId: eventIdParam,
              userId: userIdParam,
              inChatEventType: inChatEventTypeParam,
              timeStamp: timeStampParam,
              inChatEventStatus: inChatEventStatusParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.inChatData.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.inChatData.attach(store);
          return object;
        }),
    UserLocalDTO: obx_int.EntityDefinition<UserLocalDTO>(
        model: _entities[3],
        toOneRelations: (UserLocalDTO object) => [],
        toManyRelations: (UserLocalDTO object) => {},
        getId: (UserLocalDTO object) => object.id,
        setId: (UserLocalDTO object, int id) {
          object.id = id;
        },
        objectToFB: (UserLocalDTO object, fb.Builder fbb) {
          final nicknameOffset = fbb.writeString(object.nickname);
          final stateMsgOffset = object.stateMsg == null
              ? null
              : fbb.writeString(object.stateMsg!);
          final profileUrlOffset = object.profileUrl == null
              ? null
              : fbb.writeString(object.profileUrl!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.userId);
          fbb.addOffset(2, nicknameOffset);
          fbb.addOffset(3, stateMsgOffset);
          fbb.addOffset(4, profileUrlOffset);
          fbb.addFloat64(5, object.mannerTemperature);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final userIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final nicknameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final stateMsgParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final profileUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final mannerTemperatureParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final object = UserLocalDTO(
              userId: userIdParam,
              nickname: nicknameParam,
              stateMsg: stateMsgParam,
              profileUrl: profileUrlParam,
              mannerTemperature: mannerTemperatureParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [InChatDataLocalDTO] entity fields to define ObjectBox queries.
class InChatDataLocalDTO_ {
  /// See [InChatDataLocalDTO.id].
  static final id =
      obx.QueryIntegerProperty<InChatDataLocalDTO>(_entities[0].properties[0]);

  /// See [InChatDataLocalDTO.dataId].
  static final dataId =
      obx.QueryStringProperty<InChatDataLocalDTO>(_entities[0].properties[1]);

  /// See [InChatDataLocalDTO.inChatDataType].
  static final inChatDataType =
      obx.QueryStringProperty<InChatDataLocalDTO>(_entities[0].properties[2]);

  /// See [InChatDataLocalDTO.contents].
  static final contents =
      obx.QueryStringProperty<InChatDataLocalDTO>(_entities[0].properties[3]);
}

/// [InChatEventListLocalDTO] entity fields to define ObjectBox queries.
class InChatEventListLocalDTO_ {
  /// See [InChatEventListLocalDTO.id].
  static final id = obx.QueryIntegerProperty<InChatEventListLocalDTO>(
      _entities[1].properties[0]);

  /// See [InChatEventListLocalDTO.roomId].
  static final roomId = obx.QueryStringProperty<InChatEventListLocalDTO>(
      _entities[1].properties[1]);

  /// see [InChatEventListLocalDTO.userList]
  static final userList =
      obx.QueryRelationToMany<InChatEventListLocalDTO, UserLocalDTO>(
          _entities[1].relations[0]);

  /// see [InChatEventListLocalDTO.inChatEventList]
  static final inChatEventList =
      obx.QueryRelationToMany<InChatEventListLocalDTO, InChatEventLocalDTO>(
          _entities[1].relations[1]);
}

/// [InChatEventLocalDTO] entity fields to define ObjectBox queries.
class InChatEventLocalDTO_ {
  /// See [InChatEventLocalDTO.id].
  static final id =
      obx.QueryIntegerProperty<InChatEventLocalDTO>(_entities[2].properties[0]);

  /// See [InChatEventLocalDTO.eventId].
  static final eventId =
      obx.QueryIntegerProperty<InChatEventLocalDTO>(_entities[2].properties[1]);

  /// See [InChatEventLocalDTO.userId].
  static final userId =
      obx.QueryStringProperty<InChatEventLocalDTO>(_entities[2].properties[2]);

  /// See [InChatEventLocalDTO.inChatEventType].
  static final inChatEventType =
      obx.QueryStringProperty<InChatEventLocalDTO>(_entities[2].properties[3]);

  /// See [InChatEventLocalDTO.timeStamp].
  static final timeStamp =
      obx.QueryDateProperty<InChatEventLocalDTO>(_entities[2].properties[4]);

  /// See [InChatEventLocalDTO.inChatEventStatus].
  static final inChatEventStatus =
      obx.QueryStringProperty<InChatEventLocalDTO>(_entities[2].properties[5]);

  /// See [InChatEventLocalDTO.inChatData].
  static final inChatData =
      obx.QueryRelationToOne<InChatEventLocalDTO, InChatDataLocalDTO>(
          _entities[2].properties[6]);
}

/// [UserLocalDTO] entity fields to define ObjectBox queries.
class UserLocalDTO_ {
  /// See [UserLocalDTO.id].
  static final id =
      obx.QueryIntegerProperty<UserLocalDTO>(_entities[3].properties[0]);

  /// See [UserLocalDTO.userId].
  static final userId =
      obx.QueryIntegerProperty<UserLocalDTO>(_entities[3].properties[1]);

  /// See [UserLocalDTO.nickname].
  static final nickname =
      obx.QueryStringProperty<UserLocalDTO>(_entities[3].properties[2]);

  /// See [UserLocalDTO.stateMsg].
  static final stateMsg =
      obx.QueryStringProperty<UserLocalDTO>(_entities[3].properties[3]);

  /// See [UserLocalDTO.profileUrl].
  static final profileUrl =
      obx.QueryStringProperty<UserLocalDTO>(_entities[3].properties[4]);

  /// See [UserLocalDTO.mannerTemperature].
  static final mannerTemperature =
      obx.QueryDoubleProperty<UserLocalDTO>(_entities[3].properties[5]);
}
