import '../../../model/post/dto/post_dto.dart';

Future<List<PostDTO>> getLatestPostDummy(String? lastPostId) async {
  await Future.delayed(const Duration(seconds: 1), null);
  return [
    PostDTO(
      id: 3,
      gatheringCategory: '번개',
      title: '안녕하세요',
      locationId: 2,
      gatheringDate: DateTime(2024),
      contents: '안녕하세요안녕하세요',
      currentPeopleNum: 3,
      peopleNum: 5,
      currentMaleNum: 1,
      maleNum: 3,
      currentFemaleNum: 2,
      femaleNum: 2,
      ageFrom: 1,
      ageTo: 1,
      onlyMyFriends: true,
      genderRestriction: 'NONE',
      mannerRestriction: true,
      ageRestriction: true,
    ),
    PostDTO(
      id: 3,
      gatheringCategory: '번개',
      title: '안녕하세요',
      locationId: 2,
      gatheringDate: DateTime(2024),
      contents: '안녕하세요안녕하세요',
      currentPeopleNum: 4,
      peopleNum: 5,
      currentMaleNum: 4,
      maleNum: 5,
      currentFemaleNum: 0,
      femaleNum: 0,
      ageFrom: 2,
      ageTo: 5,
      onlyMyFriends: true,
      genderRestriction: 'MALE',
      mannerRestriction: true,
      ageRestriction: true,
    ),
    PostDTO(
      id: 3,
      gatheringCategory: '번개',
      title: '안녕하세요',
      locationId: 2,
      gatheringDate: DateTime(2024),
      contents: '안녕하세요안녕하세요',
      currentPeopleNum: 3,
      peopleNum: 5,
      currentMaleNum: 2,
      maleNum: 3,
      currentFemaleNum: 2,
      femaleNum: 2,
      ageFrom: 5,
      ageTo: 6,
      onlyMyFriends: true,
      genderRestriction: 'GENERAL',
      mannerRestriction: true,
      ageRestriction: false,
    ),
  ];
}
