// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2TIDDB8mNtBhhBo3_cdydlOVxxR3--rI',
    appId: '1:477385401612:android:d027eb35803b79e6931529',
    messagingSenderId: '477385401612',
    projectId: 'sottie-45d95',
    storageBucket: 'sottie-45d95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANlJzvhTYErJwoctTkBZIE1rGUNFwn6Y8',
    appId: '1:477385401612:ios:7d8cce7ba99a12c0931529',
    messagingSenderId: '477385401612',
    projectId: 'sottie-45d95',
    storageBucket: 'sottie-45d95.appspot.com',
    iosBundleId: 'com.sottie.sottieFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANlJzvhTYErJwoctTkBZIE1rGUNFwn6Y8',
    appId: '1:477385401612:ios:7d8cce7ba99a12c0931529',
    messagingSenderId: '477385401612',
    projectId: 'sottie-45d95',
    storageBucket: 'sottie-45d95.appspot.com',
    iosBundleId: 'com.sottie.sottieFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYbeL2u0ZstbpmGTwgEeq3wtWrNOxtQeM',
    appId: '1:477385401612:web:006d957c8555d453931529',
    messagingSenderId: '477385401612',
    projectId: 'sottie-45d95',
    authDomain: 'sottie-45d95.firebaseapp.com',
    storageBucket: 'sottie-45d95.appspot.com',
    measurementId: 'G-79ZC1WYC6X',
  );
}
